# Generated by Django 5.2.5 on 2025-08-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
